First, let's load the data from the train file:

In [83]:
import pandas as pd
import numpy as np

csv_train = pd.read_csv('train.csv')
csv_train

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N   
1           100003       0         Cash loans           F            N   
2           100004       0    Revolving loans           M            Y   
3           100006       0         Cash loans           F            N   
4           100007       0         Cash loans           M            N   
...            ...     ...                ...         ...          ...   
307506      456251       0         Cash loans           M            N   
307507      456252       0         Cash loans           F            N   
307508      456253       0         Cash loans           F            N   
307509      456254       1         Cash loans           F            N   
307510      456255       0         Cash loans           F            N   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                    Y             0          202500.0    406597.5   
1                    N             0          270000.0   1293502.5   
2                    Y             0           67500.0    135000.0   
3                    Y             0          135000.0    312682.5   
4                    Y             0          121500.0    513000.0   
...                ...           ...               ...         ...   
307506               N             0          157500.0    254700.0   
307507               Y             0           72000.0    269550.0   
307508               Y             0          153000.0    677664.0   
307509               Y             0          171000.0    370107.0   
307510               N             0          157500.0    675000.0   

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
0           24700.5  ...                 0                0                0   
1           35698.5  ...                 0                0                0   
2            6750.0  ...                 0                0                0   
3           29686.5  ...                 0                0                0   
4           21865.5  ...                 0                0                0   
...             ...  ...               ...              ...              ...   
307506      27558.0  ...                 0                0                0   
307507      12001.5  ...                 0                0                0   
307508      29979.0  ...                 0                0                0   
307509      20205.0  ...                 0                0                0   
307510      49117.5  ...                 0                0                0   

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                     0                        0.0                       0.0   
1                     0                        0.0                       0.0   
2                     0                        0.0                       0.0   
3                     0                        NaN                       NaN   
4                     0                        0.0                       0.0   
...                 ...                        ...                       ...   
307506                0                        NaN                       NaN   
307507                0                        NaN                       NaN   
307508                0                        1.0                       0.0   
307509                0                        0.0                       0.0   
307510                0                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                              0.0                        0.0   
1                              0.0                        0.0   
2                              0.0                        0.0   
3                              NaN                        NaN   
4                              

In [84]:
csv_test = pd.read_csv('test.csv')
csv_test

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0          100001         Cash loans           F            N               Y   
1          100005         Cash loans           M            N               Y   
2          100013         Cash loans           M            Y               Y   
3          100028         Cash loans           F            N               Y   
4          100038         Cash loans           M            Y               N   
...           ...                ...         ...          ...             ...   
48739      456221         Cash loans           F            N               Y   
48740      456222         Cash loans           F            N               N   
48741      456223         Cash loans           F            Y               Y   
48742      456224         Cash loans           M            N               N   
48743      456250         Cash loans           F            Y               N   

       CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                 0          135000.0    568800.0      20560.5   
1                 0           99000.0    222768.0      17370.0   
2                 0          202500.0    663264.0      69777.0   
3                 2          315000.0   1575000.0      49018.5   
4                 1          180000.0    625500.0      32067.0   
...             ...               ...         ...          ...   
48739             0          121500.0    412560.0      17473.5   
48740             2          157500.0    622413.0      31909.5   
48741             1          202500.0    315000.0      33205.5   
48742             0          225000.0    450000.0      25128.0   
48743             0          135000.0    312768.0      24709.5   

       AMT_GOODS_PRICE  ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19  \
0             450000.0  ...                0                0   
1             180000.0  ...                0                0   
2             630000.0  ...                0                0   
3            1575000.0  ...                0                0   
4             625500.0  ...                0                0   
...                ...  ...              ...              ...   
48739         270000.0  ...                0                0   
48740         495000.0  ...                0                0   
48741         315000.0  ...                0                0   
48742         450000.0  ...                0                0   
48743         270000.0  ...                0                0   

      FLAG_DOCUMENT_20 FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR  \
0                    0                0                        0.0   
1                    0                0                        0.0   
2                    0                0                        0.0   
3                    0                0                        0.0   
4                    0                0                        NaN   
...                ...              ...                        ...   
48739                0                0                        0.0   
48740                0                0                        NaN   
48741                0                0                        0.0   
48742                0                0                        0.0   
48743                0                0                        0.0   

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                            0.0                         0.0   
1                            0.0                         0.0   
2                            0.0                         0.0   
3                            0.0                         0.0   
4                            NaN                         NaN   
...                          ...                         ...   
48739                        0.0                         0.0   
48740                        NaN                         NaN   
48741                        0.0           

In [93]:
for col in csv_train:
    if csv_train[col].dtype == object:
        unique_train = pd.unique(csv_train[col])
        unique_test = pd.unique(csv_test[col])
        if not np.array_equal((unique_train), (unique_test)):
            print('train', unique_train)
            print('test', unique_test)

train ['M' 'F' 'XNA']
test ['F' 'M']
train ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']
test ['Unaccompanied' nan 'Family' 'Spouse, partner' 'Group of people'
 'Other_B' 'Children' 'Other_A']
train ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
test ['Working' 'State servant' 'Pensioner' 'Commercial associate'
 'Businessman' 'Student' 'Unemployed']
train ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
test ['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
train ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
test ['Married' 'Single / not married' 'Civil marriage' 'Widow' 'Separated']
train ['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
test

Let's drop the IDs:

In [56]:
csv_train = csv_train.drop('SK_ID_CURR', axis=1)
csv_test = csv_test.drop('SK_ID_CURR', axis=1)

Let's write a one-hot encode function for categorical types:

In [57]:
def one_hot_encode(df):
    labels = sorted(pd.unique(df))
    count = len(labels)
    labels_dict = {labels[i]: i for i in range(count)}

    result = np.empty((df.shape[0], count - 1), dtype=np.uint8)
    for i, row in enumerate(df):
        num = labels_dict[row]
        for j in range(count - 1):
            result[i, j] = 1 if j == num else 0

    return result

Now let's check if it works:

In [58]:
one_hot_encode(csv_train['NAME_CONTRACT_TYPE'])

array([[1],
       [1],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=uint8)

Let's look at the data in general:

In [60]:
for col in csv_train:
    print(col, pd.unique(csv_train[col]))

TARGET [1 0]
NAME_CONTRACT_TYPE ['Cash loans' 'Revolving loans']
CODE_GENDER ['M' 'F' 'XNA']
FLAG_OWN_CAR ['N' 'Y']
FLAG_OWN_REALTY ['Y' 'N']
CNT_CHILDREN [ 0  1  2  3  4  7  5  6  8  9 11 12 10 19 14]
AMT_INCOME_TOTAL [202500.  270000.   67500.  ...  96768.  546250.5 113062.5]
AMT_CREDIT [ 406597.5 1293502.5  135000.  ...  181989.   743863.5 1391130. ]
AMT_ANNUITY [24700.5 35698.5  6750.  ... 71986.5 58770.  77809.5]
AMT_GOODS_PRICE [ 351000.  1129500.   135000.  ...  453465.   143977.5  743863.5]
NAME_TYPE_SUITE ['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' nan
 'Other_B' 'Group of people']
NAME_INCOME_TYPE ['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
NAME_EDUCATION_TYPE ['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
NAME_FAMILY_STATUS ['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
NAME_HOUSING_

Let's look at the highest correlations between columns:

In [61]:
for col_i in csv_train:
    if csv_train[col_i].dtype == object:
        continue
    for col_j in csv_train:
        if csv_train[col_j].dtype == object or col_i == col_j:
            continue
        cc = np.corrcoef(csv_train[col_i], csv_train[col_j])[0, 1]
        if cc > 0.5:
            print(col_i, col_j, cc)

DAYS_BIRTH FLAG_EMP_PHONE 0.619887696202353
DAYS_EMPLOYED FLAG_DOCUMENT_6 0.5974844373735059
FLAG_EMP_PHONE DAYS_BIRTH 0.619887696202353
REGION_RATING_CLIENT REGION_RATING_CLIENT_W_CITY 0.9508422141646367
REGION_RATING_CLIENT_W_CITY REGION_RATING_CLIENT 0.9508422141646368
REG_REGION_NOT_WORK_REGION LIVE_REGION_NOT_WORK_REGION 0.8606267802832693
LIVE_REGION_NOT_WORK_REGION REG_REGION_NOT_WORK_REGION 0.8606267802832693
REG_CITY_NOT_WORK_CITY LIVE_CITY_NOT_WORK_CITY 0.8255747229688973
LIVE_CITY_NOT_WORK_CITY REG_CITY_NOT_WORK_CITY 0.8255747229688972
FLAG_DOCUMENT_6 DAYS_EMPLOYED 0.5974844373735059


Let's fill all the nan values in string columns with the string 'XNA':

In [62]:
for col in csv_train:
    if csv_train[col].dtype == object:
        csv_train[col] = csv_train[col].fillna('XNA')

Let's check the data again:

In [63]:
for col in csv_train:
    print(col, pd.unique(csv_train[col].sort_values()))

TARGET [0 1]
NAME_CONTRACT_TYPE ['Cash loans' 'Revolving loans']
CODE_GENDER ['F' 'M' 'XNA']
FLAG_OWN_CAR ['N' 'Y']
FLAG_OWN_REALTY ['N' 'Y']
CNT_CHILDREN [ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 19]
AMT_INCOME_TOTAL [2.565000e+04 2.610000e+04 2.646000e+04 ... 1.350000e+07 1.800009e+07
 1.170000e+08]
AMT_CREDIT [  45000.    47970.    48519.  ... 4027680.  4031032.5 4050000. ]
AMT_ANNUITY [  1615.5   1980.    1993.5 ... 230161.5 258025.5      nan]
AMT_GOODS_PRICE [  40500.   45000.   49500. ... 3825000. 4050000.      nan]
NAME_TYPE_SUITE ['Children' 'Family' 'Group of people' 'Other_A' 'Other_B'
 'Spouse, partner' 'Unaccompanied' 'XNA']
NAME_INCOME_TYPE ['Businessman' 'Commercial associate' 'Maternity leave' 'Pensioner'
 'State servant' 'Student' 'Unemployed' 'Working']
NAME_EDUCATION_TYPE ['Academic degree' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Secondary / secondary special']
NAME_FAMILY_STATUS ['Civil marriage' 'Married' 'Separated' 'Single / not married' 'Unkno

The column DAYS_EMPLOYED seems to have an invalid value in it. Let's replace it with NaN.

In [64]:
csv_train['DAYS_EMPLOYED'].value_counts()

 365243    55374
-200         156
-224         152
-230         151
-199         151
           ...  
-13961         1
-11827         1
-10176         1
-9459          1
-8694          1
Name: DAYS_EMPLOYED, Length: 12574, dtype: int64

In [65]:
csv_train['DAYS_EMPLOYED'] = csv_train['DAYS_EMPLOYED'].replace(365243, np.nan)

It seems like the AMT_REQ_CREDIT_BUREAU_QRT column has one significant outlier. Let's remove it:

In [66]:
csv_train['AMT_REQ_CREDIT_BUREAU_QRT'].value_counts()

0.0      215417
1.0       33862
2.0       14412
3.0        1717
4.0         476
5.0          64
6.0          28
8.0           7
7.0           7
261.0         1
19.0          1
Name: AMT_REQ_CREDIT_BUREAU_QRT, dtype: int64

In [67]:
csv_train = csv_train[csv_train['AMT_REQ_CREDIT_BUREAU_QRT'] != 261.0]
csv_train = csv_train[csv_train['AMT_REQ_CREDIT_BUREAU_QRT'] != 19.0]

Let's move the targets to a separate numpy array:

In [68]:
target = csv_train['TARGET']
target = target.astype(np.uint8)
target = target.to_numpy()

And remove them from the original dataset:

In [74]:
csv_train = csv_train.drop('TARGET', axis=1)

Let's copy all the columns with categorical values to a separate array and remove them from the dataset:

In [76]:
cols = []
for col in csv_train:
    if csv_train[col].dtype == object:
        cols.append(csv_train[col])
        csv_train = csv_train.drop(col, axis=1)

At this point we can convert the dataset to a numpy array:

In [77]:
data = csv_train.to_numpy()

In [78]:
data.shape

(307509, 104)

Let's go over all the columns and fill NaN values with the mean of the column, append a new column that indicates whether there was a NaN value in the original dataset, and normalize the data:

In [79]:
data = data.astype(np.float64)
new_cols = np.empty((data.shape[0], 0), np.uint8)
for i in range(data.shape[1]):
    new_col = np.isnan(data[:, i])
    mean = np.nanmean(data[:, i])
    data[:, i] = np.nan_to_num(data[:, i], nan=mean)
    data[:, i] = (data[:, i] - data[:, i].min()) / (data[:, i].max() - data[:, i].min())
    if any(new_col):
        new_col = new_col.astype(np.uint8)
        new_cols = np.concatenate([new_cols, new_col.reshape((new_col.shape[0], 1))], axis=-1)
data = np.concatenate([data, new_cols], axis=-1)

Before one-hot encoding the categorical columns, let's compare the encoding to the ones we would get from the test dataset:

In [82]:
len(cols)

0

Now let's one-hot encode all the categorical columns and append them to the data:

In [48]:
for col in cols:
    new_cols = one_hot_encode(col)
    data = np.concatenate((data, new_cols), axis=1)

In [49]:
data.shape

(307509, 296)

In [50]:
for i in range(data.shape[1]):
    cc = np.corrcoef(data[:, i], target)[0, 1]
    if cc > 0.05:
        print(i, cc)

6 0.07824923871017524
7 0.07007052390056724
9 0.05145102880899517
18 0.058901147627345225
19 0.060894432122081045
25 0.05100094340143243
77 0.05520801656565238
167 0.0547210061532838
178 0.05747274385372976


Now we have two numpy arrays: data and targets, that only consist of normalized float32 values, and we can finally use it to train a model. First, let's construct a simple regression model, train it, and look at the results:

In [51]:
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(296,)),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.BinaryFocalCrossentropy(),
                metrics=tf.keras.metrics.AUC())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [52]:
np.unique(target, return_counts=True)

(array([0, 1], dtype=uint8), array([282685,  24824]))

In [53]:
model.fit(data, target, batch_size=64, epochs=100, class_weight={0: 0.9, 1: 0.1},
          callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)])

Epoch 1/100


2023-03-26 22:07:32.890619: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_242"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\020FlatMapDataset:4"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PRODUCT


4805/4805 [==============================] - 52s 11ms/step - loss: 0.0142 - auc_1: 0.6521
Epoch 2/100
4805/4805 [==============================] - 52s 11ms/step - loss: 0.0129 - auc_1: 0.7351
Epoch 3/100
4805/4805 [==============================] - 51s 11ms/step - loss: 0.0129 - auc_1: 0.7397
Epoch 4/100
4805/4805 [==============================] - 55s 12ms/step - loss: 0.0129 - auc_1: 0.7404
Epoch 5/100
4805/4805 [==============================] - 56s 12ms/step - loss: 0.0129 - auc_1: 0.7408
Epoch 6/100
4805/4805 [==============================] - 56s 12ms/step - loss: 0.0129 - auc_1: 0.7402
Epoch 7/100
4805/4805 [==============================] - 57s 12ms/step - loss: 0.0129 - auc_1: 0.7405
Epoch 8/100
4805/4805 [==============================] - 57s 12ms/step - loss: 0.0129 - auc_1: 0.7408
Epoch 9/100
4805/4805 [==============================] - 57s 12ms/step - loss: 0.0129 - auc_1: 0.7416
Epoch 10/100
4805/4805 [==============================] - 58s 12ms/step - loss: 0.0129 - auc_1

In [38]:
pr = model.predict(data)

  67/9610 [..............................] - ETA: 21s

2023-03-24 11:59:54.418165: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


9610/9610 [==============================] - 19s 2ms/step


In [92]:
f = np.vectorize(lambda x: 0 if x < 0.5 else 1)
res = f(pr)
res = res.reshape((307510,))

In [93]:
res.shape

(307510,)

In [96]:
np.unique(res, return_counts=True)

(array([0]), array([307510]))

In [94]:
np.corrcoef(res, target)

/Users/mykytko/Library/Python/3.10/lib/python/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/mykytko/Library/Python/3.10/lib/python/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[nan, nan],
       [nan,  1.]])

In [31]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(250,)),
    tf.keras.layers.Dense(250, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=tf.keras.metrics.AUC())

In [32]:
model.fit(data, target)

2023-03-24 11:52:04.785297: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


9610/9610 [==============================] - 131s 13ms/step - loss: 0.2556 - auc_5: 0.7236


In [51]:
data2 = (data - 0.5) * 2

In [53]:
target2 = (target - 0.5) * 2

In [54]:
target2

array([ 1., -1., -1., ..., -1.,  1., -1.])

In [161]:
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(250,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005),
                loss=tf.keras.losses.BinaryFocalCrossentropy(),
                metrics=tf.keras.metrics.AUC())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [162]:
np.unique(target, return_counts=True)

(array([0, 1], dtype=int8), array([282686,  24825]))

In [165]:
model.fit(data, target, batch_size=64, epochs=100,
          callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)])

Epoch 1/100
   3/4805 [..............................] - ETA: 2:51 - loss: 0.0664 - auc_20: 0.7804

2023-03-24 15:15:15.695519: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_1035449"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:455"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

4805/4805 [==============================] - 84s 17ms/step - loss: 0.0690 - auc_20: 0.7334
Epoch 2/100
4805/4805 [==============================] - 86s 18ms/step - loss: 0.0688 - auc_20: 0.7363
Epoch 3/100
4805/4805 [==============================] - 86s 18ms/step - loss: 0.0686 - auc_20: 0.7381
Epoch 4/100
4805/4805 [==============================] - 90s 19ms/step - loss: 0.0686 - auc_20: 0.7388
Epoch 5/100
4805/4805 [==============================] - 92s 19ms/step - loss: 0.0684 - auc_20: 0.7407
Epoch 6/100
4805/4805 [==============================] - 91s 19ms/step - loss: 0.0684 - auc_20: 0.7410
Epoch 7/100
4805/4805 [==============================] - 94s 19ms/step - loss: 0.0683 - auc_20: 0.7425
Epoch 8/100
4805/4805 [==============================] - 91s 19ms/step - loss: 0.0683 - auc_20: 0.7434
Epoch 9/100
4805/4805 [==============================] - 93s 19ms/step - loss: 0.0681 - auc_20: 0.7448
Epoch 10/100
4805/4805 [==============================] - 85s 18ms/step - loss: 0.068

In [167]:
np.unique(target, return_counts=True)

(array([0, 1], dtype=int8), array([282686,  24825]))

In [168]:
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model2 = tf.keras.Sequential([
        tf.keras.Input(shape=(250,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    model2.compile(optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.BinaryFocalCrossentropy(),
                metrics=tf.keras.metrics.AUC())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [169]:
model2.fit(data, target, batch_size=64, epochs=100, class_weight={0: 0.1, 1: 0.9},
          callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)])

Epoch 1/100


2023-03-24 16:32:57.761210: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_1709185"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:563"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

4805/4805 [==============================] - 81s 16ms/step - loss: 0.0254 - auc_21: 0.7192
Epoch 2/100
4805/4805 [==============================] - 80s 17ms/step - loss: 0.0250 - auc_21: 0.7358
Epoch 3/100
4805/4805 [==============================] - 79s 17ms/step - loss: 0.0248 - auc_21: 0.7396
Epoch 4/100
4805/4805 [==============================] - 81s 17ms/step - loss: 0.0248 - auc_21: 0.7416
Epoch 5/100
2878/4805 [================>.............] - ETA: 33s - loss: 0.0247 - auc_21: 0.7429

KeyboardInterrupt: 

In [170]:
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model3 = tf.keras.Sequential([
        tf.keras.Input(shape=(250,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    model3.compile(optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.BinaryFocalCrossentropy(),
                metrics=tf.keras.metrics.AUC())

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)


In [171]:
model3.fit(data, target, batch_size=64, epochs=100, class_weight={0: 0.9, 1: 0.1},
          callbacks=[tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)])

Epoch 1/100


2023-03-24 16:41:29.957196: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_1821208"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:600"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

4805/4805 [==============================] - 86s 18ms/step - loss: 0.0134 - auc_22: 0.7134
Epoch 2/100
4805/4805 [==============================] - 80s 17ms/step - loss: 0.0130 - auc_22: 0.7347
Epoch 3/100
4747/4805 [============================>.] - ETA: 0s - loss: 0.0129 - auc_22: 0.7368

KeyboardInterrupt: 

In [172]:
pr = model.predict(data)

   1/9610 [..............................] - ETA: 26:38

2023-03-24 16:45:49.893957: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_1894304"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:631"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

9610/9610 [==============================] - 39s 4ms/step


In [173]:
pr2 = model2.predict(data2)

  11/9610 [..............................] - ETA: 50s  

2023-03-24 16:46:38.249654: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_1981015"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:655"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

9610/9610 [==============================] - 38s 4ms/step


In [174]:
pr3 = model3.predict(data)

   8/9610 [..............................] - ETA: 1:14 

2023-03-24 16:47:17.274222: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:776] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: -2
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_2067726"
    }
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\022FlatMapDataset:679"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
experimental_type {
  type_id: TFT_PRODUCT
  args {
    type_id: TFT_DATASET
    args {
      type_id: TFT_PR

9610/9610 [==============================] - 40s 4ms/step


In [181]:
pr.resize((pr.shape[0],))
pr2.resize((pr2.shape[0],))
pr3.resize((pr3.shape[0],))

In [180]:
np.corrcoef(pr, target)

array([[1.        , 0.25593256],
       [0.25593256, 1.        ]])

In [183]:
pr2.shape

(307510,)

In [184]:
target.shape

(307511,)

In [185]:
pr3.shape

(307511,)

In [186]:
np.corrcoef(pr3, target)

array([[1.        , 0.25855857],
       [0.25855857, 1.        ]])

In [182]:
np.corrcoef(pr2, target)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 307510 and the array at index 1 has size 307511

In [65]:
pr.reshape(pr.shape[0])

array([0.46515217, 0.19805619, 0.18425995, ..., 0.2249432 , 0.25992984,
       0.2618208 ], dtype=float32)

In [66]:
np.corrcoef(target, pr.reshape(pr.shape[0]))

array([[1.        , 0.25663899],
       [0.25663899, 1.        ]])